### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by pllim** [scientific-python/action-towncrier-changelog#13]
@bsipocz , can we release v1 now that #9 is merged, or you want something else in prior? cc @larsoner

**Comment by larsoner** [comment]
The changes from #10 would definitely be backward incompatible. Could do that as part of a v2 or a v1. I could probably make some or most of the changes fairly quickly but probably better to cut a v1 in case the PR process takes a while

**Comment by pllim** [comment]
Yeah, I think it is safer to do #10 after we have proper unit tests (#11) but not sure when I can get to it, so I agree that one can wait till v2 if you don't mind. Thanks for the input!

**Comment by bsipocz** [comment]
I would say yes, do cut a v1 now, and then either do #10 as a new release on that, or call it v2 if incompatible.

**Comment by larsoner** [comment]
#10 would be backward incompat because it would require addition of a step (checkout) and config in the action itself rather than YAML for example. So would be v2 I think!

**Comment by pllim** [comment]
OK I will release.

**Comment by pllim** [comment]
Done: https://github.com/scientific-python/action-towncrier-changelog/releases/tag/v1.0.0

There is also a more generic `v1` tag that I suspect will just have to be updated when new v1.x is released in the future.

Please open issue(s) if you have problem with this new release. Thanks!
