### ISSUE TITLE
Batch PRs to update downstream

### ISSUE THREAD

**Issue by pllim** [scientific-python/action-towncrier-changelog#4]
Maybe pin to hash too?

**Comment by pllim** [comment]
Ignoring forks and archived packages, really only `astropy` is directly affected. I also updated README here in https://github.com/scientific-python/action-towncrier-changelog/commit/cb4239c72f8528265a314e43d73d470b029855b3 .

**Comment by bsipocz** [comment]
I would have assumed that sunpy uses this, too 🤷‍♀️

**Comment by pllim** [comment]
No, looks like they rolled their own at https://github.com/sunpy/sunpy/blob/main/.github/workflows/changelog_bot.yml
