### ISSUE TITLE
Consider relicensing?

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/action-towncrier-changelog#5]
By changing the org, shall we relicense, similarly as we did with doctestplus? 

Same issue is relevant for the other changelog action, but I would not duplicate the issues just to add noise.

**Comment by pllim** [comment]
Yeah, that is fine. I just don't know when I'll have time to do it, so PR is welcome! Otherwise, this goes in my queue. Thanks!

**Comment by bsipocz** [comment]
> I just don't know when I'll have time to do it, so PR is welcome

Sure, I can open a PR, just didn't want to do it without your OK.
