### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by pllim** [scientific-python/action-towncrier-changelog#7]
```
/check_changelog.py:8: DeprecationWarning: pkg_resources is deprecated as an API.
```

**Comment by pllim** [comment]
@Cadair , didn't you originally write this? Do you know how to replace with new code? Thanks!

https://github.com/scientific-python/action-towncrier-changelog/blob/cb4239c72f8528265a314e43d73d470b029855b3/check_changelog.py#L132-L138

**Comment by Cadair** [comment]
That code is (was) ripped out of the internals of towncrier. The best way to update is to copy it out again I would think.
